//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWebApiTwo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avatar
    {
        public int ID { get; set; }
        public string AvatarName { get; set; }
        public string Img { get; set; }
    }
}
