//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWebApiTwo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Dlcs = new HashSet<Dlc>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public System.DateTime RelaseDate { get; set; }
        public string Img { get; set; }
        public string BackgroundImg { get; set; }
        public Nullable<int> Platform_ID { get; set; }
        public int Developer_ID { get; set; }
    
        public virtual Developer Developer { get; set; }
        public virtual ICollection<Dlc> Dlcs { get; set; }
        public virtual Platform Platform { get; set; }
    }
}
