//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWebApiTwo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGame
    {
        public UserGame()
        {
            this.UserDlcs = new HashSet<UserDlc>();
        }
    
        public int ID { get; set; }
        public string UserTitle { get; set; }
        public int Rate { get; set; }
        public string Img { get; set; }
        public string BackgroundImg { get; set; }
        public int User_ID { get; set; }
        public string List { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<UserDlc> UserDlcs { get; set; }
    }
}
